import type { Narrative } from "@/config/theme-narratives";
import type { LayoutSpec } from "@/types/theme-kit/layout";
import type { THEME_FEELS_V4 } from "@/config/theme-feels";
import type { TONES } from "@/config/theme-tones";

type Feel = (typeof THEME_FEELS_V4)[0];
type Tone = (typeof TONES)[0];

export interface ThemeIdentity {
  /** Short two-word theme name (already generated by theme-name.ts; passed in). */
  name: string;
  /** One-line description templated from feel + narrative descriptors. */
  tagline: string;
  /** Use-case suggestion, e.g. "fintech dashboards selling trust". */
  designedFor: string;
  /** Optional design-system analog, e.g. "feels like Linear meets Apple Calendar". */
  designSystemRef?: string;
}

const NARRATIVE_STORY: Record<string, string> = {
  "monochrome-accent": "one bold accent on neutral",
  "dark-signature": "a single signature color in the dark",
  "dual-accent": "two confident accents in dialogue",
  "colored-canvas": "a saturated canvas grounding everything",
  "muted-harmony": "no single color dominating",
  "tone-on-tone": "one hue family, deeply explored",
  "vibrant-clash": "two unexpected colors at full volume",
};

const USE_CASE: Record<string, string> = {
  "monochrome-accent::app-dashboard": "SaaS dashboards selling trust",
  "monochrome-accent::auth-centered": "minimal auth flows that disappear into the product",
  "monochrome-accent::editorial": "editorial reading where the writing is the brand",
  "monochrome-accent::swiss-grid": "documentation that respects the reader",
  "dark-signature::app-dashboard": "developer tools that feel like home in a dark IDE",
  "dark-signature::bento-showcase": "product showcases for night-owl creators",
  "dark-signature::auth-split": "premium signup with a bold first impression",
  "dual-accent::marketing-landing": "growth pages that convert without shouting",
  "dual-accent::auth-split": "branded onboarding for two-sided products",
  "dual-accent::bauhaus": "design tools where every block matters",
  "colored-canvas::marketing-landing": "lifestyle brands with personality",
  "colored-canvas::editorial": "magazines that own their voice",
  "colored-canvas::auth-split": "consumer auth that earns the email address",
  "muted-harmony::editorial": "long-form publications with restraint",
  "muted-harmony::app-workspace": "knowledge tools for sustained focus",
  "muted-harmony::app-settings": "settings that don't beg for attention",
  "tone-on-tone::marketing-landing": "single-product launches with clear identity",
  "tone-on-tone::bento-showcase": "portfolio sites with strong point of view",
  "vibrant-clash::marketing-landing": "creator economy products",
  "vibrant-clash::bento-showcase": "showcase pages that demand attention",
  "vibrant-clash::magazine-bento": "media brands with editorial swagger",
};

const FEEL_USE_CASE_FALLBACK: Record<string, string> = {
  noir: "products with cinematic restraint",
  cyber: "technical tools for power users",
  vibrant: "consumer products with energy",
  serene: "wellness and mindfulness products",
  elegant: "luxury and premium experiences",
  playful: "consumer apps for delight",
  industrial: "B2B tools for serious work",
  pastel: "soft consumer experiences",
  ethereal: "creative and dreamlike products",
  warm: "hospitality and community products",
  cool: "B2B SaaS with poise",
};

const GENERIC_USE_CASE = "any product with a clear point of view";

function descriptorFromFeel(feel: Feel): string {
  return feel.description.replace(/[.!?]+$/, "").replace(/^./, (c) => c.toLowerCase());
}

export interface BuildIdentityParams {
  name: string;
  feel: Feel;
  tone: Tone;
  narrative: Narrative;
  layout: LayoutSpec;
}

export function buildIdentity(params: BuildIdentityParams): ThemeIdentity {
  const { name, feel, narrative, layout } = params;
  const tagline = `${descriptorFromFeel(feel)} with ${NARRATIVE_STORY[narrative.id] ?? "a clear color story"}`;
  const designedFor =
    USE_CASE[`${narrative.id}::${layout.archetype}`] ??
    FEEL_USE_CASE_FALLBACK[feel.id] ??
    GENERIC_USE_CASE;

  return {
    name,
    tagline,
    designedFor,
  };
}
