export const THEME_FEELS_V4 = [
  {
    id: "ethereal",
    name: "Ethereal",
    description: "Mystical and dreamy with soft, otherworldly colors",
    lightnessRange: [0.35, 0.75],
    chromaRange: [0.06, 0.16],
    preferredHues: [240, 280, 320, 200],
  },
  {
    id: "vibrant",
    name: "Vibrant",
    description: "Bold and energetic with high-contrast colors",
    lightnessRange: [0.3, 0.7],
    chromaRange: [0.15, 0.25],
    preferredHues: [0, 30, 120, 240],
  },
  {
    id: "serene",
    name: "Serene",
    description: "Calm and peaceful with muted, sophisticated tones",
    lightnessRange: [0.4, 0.85],
    chromaRange: [0.02, 0.07],
    preferredHues: [200, 220, 180, 60],
  },
  {
    id: "warm",
    name: "Warm",
    description: "Cozy and inviting with earth-toned colors",
    lightnessRange: [0.4, 0.7],
    chromaRange: [0.08, 0.18],
    preferredHues: [20, 40, 60, 300],
  },
  {
    id: "cool",
    name: "Cool",
    description: "Fresh and modern with cool-toned colors",
    lightnessRange: [0.5, 0.8],
    chromaRange: [0.06, 0.16],
    preferredHues: [180, 200, 240, 280],
  },
  {
    id: "elegant",
    name: "Elegant",
    description: "Sophisticated and refined with rich, deep colors",
    lightnessRange: [0.2, 0.6],
    chromaRange: [0.05, 0.15],
    preferredHues: [260, 280, 20, 340],
  },
  {
    id: "playful",
    name: "Playful",
    description: "Fun and cheerful with bright, happy colors",
    lightnessRange: [0.5, 0.85],
    chromaRange: [0.12, 0.22],
    preferredHues: [300, 60, 120, 200],
  },
  {
    id: "noir",
    name: "Noir",
    description: "Dark, moody, and cinematic with low-light ambiance",
    lightnessRange: [0.1, 0.4],
    chromaRange: [0.02, 0.08],
    preferredHues: [260, 280, 20, 0],
  },
  {
    id: "sunset",
    name: "Sunset",
    description: "Radiant and dreamy with shifting warm gradients and sunlight-inspired tones",
    lightnessRange: [0.5, 0.8],
    chromaRange: [0.11, 0.22],
    preferredHues: [30, 45, 20, 340],
  },
  {
    id: "nature",
    name: "Nature",
    description: "Organic and grounded with foliage and soil tones",
    lightnessRange: [0.35, 0.7],
    chromaRange: [0.08, 0.18],
    preferredHues: [100, 120, 40, 20],
  },
  {
    id: "cyber",
    name: "Cyber",
    description: "High-tech and futuristic with neon and digital tones",
    lightnessRange: [0.4, 0.75],
    chromaRange: [0.15, 0.25],
    preferredHues: [300, 180, 220, 0],
  },
  {
    id: "monochrome",
    name: "Monochrome",
    description: "Classic grayscale-inspired theme with minimal hue variation",
    lightnessRange: [0.2, 0.9],
    chromaRange: [0.0, 0.03],
    preferredHues: [0, 220, 0, 220],
  },
  {
    id: "vintage",
    name: "Vintage",
    description: "Retro-inspired muted palette with nostalgic warmth",
    lightnessRange: [0.35, 0.65],
    chromaRange: [0.05, 0.12],
    preferredHues: [30, 300, 60, 340],
  },
  {
    id: "frosted",
    name: "Frosted",
    description: "Icy and delicate with crisp, translucent colors",
    lightnessRange: [0.6, 0.9],
    chromaRange: [0.04, 0.1],
    preferredHues: [200, 220, 240, 260],
  },
  {
    id: "pastel",
    name: "Pastel",
    description: "Soft and airy with gentle candy-like tones",
    lightnessRange: [0.7, 0.9],
    chromaRange: [0.05, 0.12],
    preferredHues: [40, 60, 280, 120],
  },
  {
    id: "industrial",
    name: "Industrial",
    description: "Urban and functional with rugged neutral tones",
    lightnessRange: [0.3, 0.6],
    chromaRange: [0.02, 0.08],
    preferredHues: [0, 220, 240, 60],
  },
  {
    id: "forest",
    name: "Forest",
    description: "Deep and lush with layered botanical greens",
    lightnessRange: [0.25, 0.6],
    chromaRange: [0.08, 0.16],
    preferredHues: [120, 140, 160, 100],
  },
  {
    id: "ocean",
    name: "Ocean",
    description: "Deep aquatic blues with teal and navy depths",
    lightnessRange: [0.3, 0.7],
    chromaRange: [0.1, 0.2],
    preferredHues: [190, 200, 210, 230],
  },
  {
    id: "jewel",
    name: "Jewel",
    description: "Rich gemstone tones with luxurious saturation",
    lightnessRange: [0.35, 0.65],
    chromaRange: [0.15, 0.25],
    preferredHues: [150, 270, 320, 40],
  },
  {
    id: "aurora",
    name: "Aurora",
    description: "Shifting northern lights with ethereal purples and greens",
    lightnessRange: [0.4, 0.8],
    chromaRange: [0.08, 0.18],
    preferredHues: [160, 280, 300, 140],
  },
  {
    id: "terracotta",
    name: "Terracotta",
    description: "Earthy clay and rust tones with Mediterranean warmth",
    lightnessRange: [0.35, 0.65],
    chromaRange: [0.1, 0.18],
    preferredHues: [15, 25, 35, 350],
  },
  {
    id: "midnight",
    name: "Midnight",
    description: "Deep night sky with subtle cosmic undertones",
    lightnessRange: [0.15, 0.45],
    chromaRange: [0.05, 0.12],
    preferredHues: [240, 260, 280, 220],
  },
];
